(require 'diminish)

(diminish 'paredit-mode "Par")
(diminish 'elisp-slime-nav-mode "")
(diminish 'undo-tree-mode "")
(diminish 'git-gutter-mode "")
(diminish 'volatile-highlights-mode "")
(diminish 'highlight-symbol-mode "")
(diminish 'eldoc-mode "")
(setq projectile-mode-line-lighter "Proj")
