(require 'diminish)

(diminish 'paredit-mode)
(diminish 'highlight-symbol-mode)
(diminish 'undo-tree-mode)
(diminish 'yas-minor-mode)
(diminish 'volatile-highlights-mode)
(diminish 'elisp-slime-nav-mode)
(diminish 'git-gutter-mode)
(diminish 'auto-complete-mode)
